[network]
name = "testnet"
stacks_node_rpc_url = "https://api.testnet.hiro.so"


[accounts.deployer]
# mnemonic = "cheap mutual invest blouse moon basic unable fitness library infant vast actress"
mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health outside kitten belt reform"